In [1]:
#numpy

In [1]:
!pip install numpy

In [2]:
import numpy as np
array_one=np.array([1,2,3,4,5,6])
array_one

array([1, 2, 3, 4, 5, 6])

In [3]:
type(array_one)

numpy.ndarray

In [5]:
zero_array=np.zeros((5,4))
zero_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
one_array=np.ones((3,4))
one_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
array_of_ones_int=np.ones((4,5),dtype=np.int16)
array_of_ones_int

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int16)

In [13]:
array_empty=np.empty((2,3))
array_empty

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
array_eye=np.eye(3)
array_eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
x=np.arange(20)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [22]:
array_of_even=np.arange(2,20,2)
array_of_even

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [23]:
array_of_float=np.arange(0,2,0.2)
array_of_float

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8])

In [24]:
array_2d=np.array([(2,4,6),(1,3,5)])
array_2d

array([[2, 4, 6],
       [1, 3, 5]])

In [25]:
type(array_2d)

numpy.ndarray

In [26]:
array_2d.shape

(2, 3)

In [27]:
array_2d.ndim

2

In [2]:
import numpy as np
arr = np.array([[(1, 2, 3), (4, 5, 6)], [(1, 2, 3), (4, 5, 6)]])
arr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [32]:
arr.shape

(2, 2, 3)

In [6]:
y=np.arange(6)
y

array([0, 1, 2, 3, 4, 5])

In [11]:
y=np.arange(6).reshape(2,3)
y

array([[0, 1, 2],
       [3, 4, 5]])