In [3]:
import numpy as np

In [19]:
students=np.array([['madhavi','Ujwal','Hajra','Abdul'],[56,87,98, 78],[7,78,87,56]])

In [20]:
for i in students:
    print('i=',i)

i= ['madhavi' 'Ujwal' 'Hajra' 'Abdul']
i= ['56' '87' '98' '78']
i= ['7' '78' '87' '56']


In [ ]:
Flatten function

In [8]:
for i in students.flatten():
    print(i)

madhavi
ujwal
Hajra
Abdul
56
98
78
36
76
73
90
67


In [ ]:
#by default  row base iteration will happen

In [ ]:
#column wise iteration

In [12]:
for x in students.flatten(order='f'):
    print(x)

madhavi
56
76
ujwal
98
73
Hajra
78
90
Abdul
36
67


In [ ]:
Alteranative approach to flatten function

In [ ]:
nditer :  It is builtin methode in numpy and very much compatible with Numpy library
    its ROW based iteration

In [15]:
x=np.arange(12).reshape(3,4)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [16]:
for i in np.nditer(x):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [ ]:
# for Column based iteration 

In [17]:
for i in np.nditer(x, order='f'):
    print(i)


0
4
8
1
5
9
2
6
10
3
7
11
